In [32]:
import sys
import numpy as np

sys.path.append("/home/louis/workspace/robinson-shensted")
from algo import (
    Permutation,
    roby_insertion,
    janvier_insertion,
    permutation_to_growth_diagram,
    permutation_to_chains_gd,
    permutation_to_chains,
    standard_YFT_to_chain,
    chain_to_path_tableau,
    chain_to_standard_YFT,
    chains_to_growth_diagram,
    evacuation
)

### Permutation

In [25]:
p = Permutation([7, 3, 3-2, 5, 8, 4, 6, 2])
p._display_matrix()

[0. 0. 0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0. 0. 0. 0.]


### Growth Diagram and chains

In [26]:
np.rot90(permutation_to_growth_diagram(p))

array([[   0,    1,   11,   21,   22,  212,  222, 2122, 2222],
       [   0,    1,    1,    2,   12,   22,  122,  222, 2212],
       [   0,    1,    1,    2,   12,   22,   22,  212,  222],
       [   0,    1,    1,    2,    2,   12,   12,   22,  122],
       [   0,    1,    1,    2,    2,   12,   12,   22,   22],
       [   0,    1,    1,    2,    2,    2,    2,   21,   21],
       [   0,    0,    0,    1,    1,    1,    1,    2,    2],
       [   0,    0,    0,    0,    0,    0,    0,    1,    1],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0]])

In [27]:
cA, cB = permutation_to_chains_gd(p)
print(cA)
print(cB)

[0, 1, 11, 21, 22, 212, 222, 2122, 2222]
[0, 1, 2, 21, 22, 122, 222, 2212, 2222]


In [28]:
cA, cB = permutation_to_chains(p)
print(cA)
print(cB)

[0, 1, 11, 21, 22, 212, 222, 2122, 2222]
[0, 1, 2, 21, 22, 122, 222, 2212, 2222]


### Paths tableaux

In [34]:
p_tabA, p_tabB = chain_to_path_tableau(cA)
print(p_tab)

IndexError: list index out of range

### Roby relations

In [29]:
invP, invQ = roby_insertion(p)
print(f"P: {invP[1]}\n   {invP[0]}\nQ: {invQ[1]}\n   {invQ[0]}")

P: [2, 6, 4, 0, 1]
   [8, 7, 5, 5, 3]
Q: [2, 2, 7, 0, 4]
   [5, 1, 6, 8, 3]


In [41]:
evacuation(p_tab)

SyntaxError: invalid syntax (4010639066.py, line 1)

### Janvier relations

In [30]:
styfP, styfQ = janvier_insertion(p)
print(f"P: {styfP[1]}\n   {styfP[0]}\nQ: {styfQ[1]}\n   {invQ[0]}")

P: [8, 7, 7, 7, 7, 7]
   [2, 6, 4, 5, 1, 3]
Q: [8, 7, 6, 4, 3, 2]
   [5, 1, 6, 8, 3]


In [44]:
standard_YFT_to_chain(styfP)

IndexError: list index out of range

In [43]:
chain_to_standard_YFT