In [1]:
import sys
import numpy as np

sys.path.append("/home/louis/workspace/robinson-shensted")
from algo import (
    Permutation,
    roby_insertion,
    janvier_insertion,
    permutation_to_growth_diagram,
    permutation_to_chains_gd,
    permutation_to_chains,
    standard_YFT_to_chain,
    chain_to_path_tableau,
    chain_to_standard_YFT,
    chains_to_growth_diagram,
    evacuation,
    display_involution
)

### Permutation

In [2]:
p = Permutation([7, 3, 1, 5, 8, 4, 6, 2])
p._display_matrix()

[0. 0. 0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0. 0. 0. 0.]


### Growth Diagram and chains

In [3]:
np.rot90(permutation_to_growth_diagram(p))

array([[   0,    1,   11,   21,   22,  212,  222, 2122, 2222],
       [   0,    1,    1,    2,   12,   22,  122,  222, 2212],
       [   0,    1,    1,    2,   12,   22,   22,  212,  222],
       [   0,    1,    1,    2,    2,   12,   12,   22,  122],
       [   0,    1,    1,    2,    2,   12,   12,   22,   22],
       [   0,    1,    1,    2,    2,    2,    2,   21,   21],
       [   0,    0,    0,    1,    1,    1,    1,    2,    2],
       [   0,    0,    0,    0,    0,    0,    0,    1,    1],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0]])

In [4]:
cA, cB = permutation_to_chains_gd(p)
print(cA)
print(cB)

[0, 1, 11, 21, 22, 212, 222, 2122, 2222]
[0, 1, 2, 21, 22, 122, 222, 2212, 2222]


In [5]:
cA, cB = permutation_to_chains(p)
print(cA)
print(cB)

[0, 1, 11, 21, 22, 212, 222, 2122, 2222]
[0, 1, 2, 21, 22, 122, 222, 2212, 2222]


### Paths tableaux

In [6]:
p_tabA, p_tabB = chain_to_path_tableau(cA)
print(p_tabA, p_tabB)

[2, 7, 5, 1] [3, 8, 6, 4]


### Roby relations

In [7]:
invP, invQ = roby_insertion(p)
display_involution(invP)

[ 2 6 4 1 ]
[ 8 7 5 3 ]


In [8]:
evacuation(invP)

([2, 7, 4, 1], [6, 8, 5, 3])

### Janvier relations

In [9]:
styfP, styfQ = janvier_insertion(p)
print(f"P: {styfP[1]}\n   {styfP[0]}\nQ: {styfQ[1]}\n   {styfQ[0]}")

P: [8, 7, 5, 3]
   [2, 6, 4, 1]
Q: [8, 7, 6, 3]
   [5, 1, 4, 2]


In [10]:
standard_YFT_to_chain(([3, 6, 1, 4, 2], [7, 0, 5, 0, 0]))

[0, 1, 2, 12, 22, 221, 2211, 21211]

In [11]:
standard_YFT_to_chain(([2, 6, 4, 1], [8, 7, 5, 3]))

[0, 1, 11, 21, 22, 212, 222, 2122, 2222]

In [12]:
print(chain_to_standard_YFT([0, 1, 11, 21, 22, 212, 222, 2122, 2222]))
print(chain_to_standard_YFT([0, 1, 2, 21, 22, 122, 222, 2212, 2222]))

([2, 6, 4, 1], [8, 7, 5, 3])
([5, 1, 4, 2], [8, 7, 6, 3])
